# Generated by Django 3.2.5 on 2021-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='des',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='des',
            field=models.CharField(default='asdfghjklertyuiopzxcvbnm', max_length=2000),
        ),
    ]
