# Generated by Django 3.2.5 on 2021-08-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210801_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('rating', models.FloatField(null=True)),
                ('video', models.CharField(max_length=3000, null=True)),
                ('des', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
